version: '3'

services:
  backend:
    image: newshive-backend
    volumes:
      - .:/src
    ports:
      - 8080:8080
    networks:
      - newshive-network
    depends_on:
      - mongo
    command: ['npm', 'run', 'dev']

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - newshive-network
    volumes:
      - ./mongo-data:/data/db

networks:
  newshive-network:
    driver: bridge

volumes:
  mongodb:
   driver: local
  mongo-data:
   driver: local
  mongo-config:
   driver: local