version: '3'

services:
  frontend:
    image: newshive-frontend
    volumes:
      - ./:/app
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - newshive-network
    command: ['npm', 'run', 'dev']

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    image: newshive-backend
    volumes:
      - ./:/newshive
    env_file:
      - backend/.env
    ports:
      - 8080:8080
    networks:
      - newshive-network
    depends_on:
      - newshive-mongo
    command: ['npm', 'run', 'dev']

  newshive-mongo:
    image: mongo:5.0
    container_name: newshive-mongo
    ports:
      - 27017:27017
    networks:
      - newshive-network
    volumes:
      - newshive-mongo:/data/db
      - newshive-mongo_config:/data/configdb

networks:
  newshive-network:
    driver: bridge

volumes:
  newshive-mongo:
   driver: local
  newshive-mongo_config:
   driver: local

  # ./mongo-data:/data/db